import FWCore.ParameterSet.Config as cms

simple = cms.EDAnalyzer("LowPtGsfElectronsAnalyzer",
                        ECALPFClusters = cms.InputTag('particleFlowClusterECAL'),
                        HCALPFClusters = cms.InputTag('particleFlowClusterHCAL'),
                        EBRecHits = cms.InputTag("ecalRecHit","EcalRecHitsEB"),
                        EERecHits = cms.InputTag("ecalRecHit","EcalRecHitsEE"),
                        PFTracks = cms.InputTag("lowPtGsfElePfTracks"),
                        preIds = cms.InputTag("lowPtGsfElectronSeeds"),
                        preIdsValueMap = cms.InputTag("lowPtGsfElectronSeeds"),
                        eleSeeds = cms.InputTag("lowPtGsfElectronSeeds"),
                        trkCandidates = cms.InputTag("lowPtGsfEleCkfTrackCandidates"),
                        gsfTracks = cms.InputTag("lowPtGsfEleGsfTracks"),
                        EGammaGsfTracks = cms.InputTag("electronGsfTracks"),
                        PFGsfTracks = cms.InputTag("lowPtGsfElePfGsfTracks"),
                        electronCaloClusters = cms.InputTag("lowPtGsfElectronSuperClusters"),
                        electronSCs = cms.InputTag("lowPtGsfElectronSuperClusters"),
                        electronSCRefs = cms.InputTag("lowPtGsfElectronSuperClusters"),
                        electronCores = cms.InputTag("lowPtGsfElectronCores"),
                        electrons = cms.InputTag("lowPtGsfElectrons"),
                        mvaIds = cms.VInputTag( cms.InputTag("lowPtGsfElectronID") ),
                        mvaSeeds = cms.VInputTag( cms.InputTag("lowPtGsfElectronSeedValueMaps:unbiased"),
                                                  cms.InputTag("lowPtGsfElectronSeedValueMaps:ptbiased") ),
                        )
