import FWCore.ParameterSet.Config as cms

features = cms.EDAnalyzer("TrackerElectronsFeatures",
                          isMC = cms.bool(True),
                          printPfBlock = cms.bool(False),
                          disableAssociation = cms.bool(False),
                          prescaleFakes = cms.double(0.08),
                          fakesMultiplier = cms.double(1.),
                          checkFromB = cms.bool(True),
                          beamspot = cms.InputTag("offlineBeamSpot"),
                          genParticles = cms.InputTag("genParticles"),
                          gsfTracks = cms.InputTag("electronGsfTracksOpen"),
                          #gsfTracks = cms.InputTag("electronGsfTracks"),
                          PFGsfTracks = cms.InputTag("pfTrackElecOpen"),
                          PFGsfFlags = cms.InputTag("pfTrackElecOpen", 'GSFFlags'),
                          PFBlocks = cms.InputTag('particleFlowBlock'),
                          PFElectrons = cms.InputTag("particleFlowEGamma"),
                          gedElectronCores = cms.InputTag("lowPtGsfElectronCores"),
                          gedElectrons = cms.InputTag("lowPtGsfElectrons"),
                          preId = cms.InputTag("trackerDrivenElectronSeedsOpen","preid"),
                          association = cms.InputTag("trackingParticleRecoTrackAsssociation"),
                          trkCandidates = cms.InputTag("electronCkfTrackCandidatesOpen"),
                          eleSeeds = cms.InputTag("trackerDrivenElectronSeedsOpen", 'SeedsForGsf'),
                          associator = cms.InputTag("quickTrackAssociatorByHits"),
                          trackingParticles = cms.InputTag("mix", "MergedTrackTruth"),
                          hitAssociation = cms.bool(False),
                          drMax = cms.double(0.02),
                          #pileup = cms.InputTag("addPileupInfo"),
                          #vertices = cms.InputTag("offlinePrimaryVertices"),
                          #generalTracks = cms.InputTag("generalTracks"),
                          )
