ranges = {
    'gen_pt' : (0, 15),
    'gen_eta' : (-3, 3),
    'dxy' : (-0.1, 0.1),
    'dxy_err' : (0, 0.1),
    'trk_pt' : (0, 15),
    'trk_eta' : (-3, 3),
    'trk_inp' : (0, 20),
    'trk_outp' : (0, 10),
    'trk_ecal_Deta' : (0, 0.2),
    'trk_ecal_Dphi' : (-0.2, 0.2),
    'e_over_p' : (0.1, 2.5),
    'trk_chi2red' : (0, 6),
    'gsf_dpt' : (0, 2),
    'trk_gsf_chiratio' : (0., 2),
    'gsf_chi2red' : (0, 4),
    'xy_sig' : (-6, 6),
    'nhits' : (0, 50),
}

beauty = {
    'gen_pt' : r'p$_T$(gen)', 
    'gen_eta' : r'$\eta$(gen)', 
    'dxy_err' : r'$\sigma$(dxy)', 
    'nhits' : r'\# of hits',
    'trk_pt' : r'p$_T$(ktf track)', 
    'trk_eta' : r'$\eta$(ktf track)', 
    'log_trkpt' : r'log$_{10}$(p$_T$)(ktf track)', 
    'trk_inp' : r'p$_{in}$(ktf track)',
    'trk_outp' : r'p$_{out}$(ktf track)', 
    'trk_eta' : r'$\eta$(ktf track)', 
    'trk_ecal_Deta': '$\Delta\eta$(ECAL, ktf track)',
    'trk_ecal_Dphi' : '$\Delta\varphi$(ECAL, ktf track)',
    'e_over_p' : 'E/p', 
    'trk_chi2red' : '$\chi^2$(ktf track)/ndf', 
    'gsf_dpt' : r'p$_T$(gsf track)',
    'trk_gsf_chiratio' : '$\chi^2$(gsf track)/$\chi^2$(ktf track)', 
    'gsf_chi2red' : '$\chi^2$(gsf track)/ndf', 
    'xy_sig' : r'$\sigma$(dxy)/dxy',
}
